# Generated by Django 3.0.3 on 2020-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20200305_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='articles_images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prev',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
