# Generated by Django 3.0.3 on 2020-03-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20200316_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='articles_images'),
        ),
    ]
